// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD280NISrkOI_EWvvSMfxHqvUGLCMpCnGk',
    appId: '1:804008888688:web:403c87e94bdc086f7a67b5',
    messagingSenderId: '804008888688',
    projectId: 'church-management-cbf7d',
    authDomain: 'church-management-cbf7d.firebaseapp.com',
    databaseURL: 'https://church-management-cbf7d-default-rtdb.firebaseio.com',
    storageBucket: 'church-management-cbf7d.appspot.com',
    measurementId: 'G-HKLTM8TCCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuQUgGKVZWAm3gskviJXIhLrIiYNoey8',
    appId: '1:804008888688:android:bd090dfdc59dae237a67b5',
    messagingSenderId: '804008888688',
    projectId: 'church-management-cbf7d',
    databaseURL: 'https://church-management-cbf7d-default-rtdb.firebaseio.com',
    storageBucket: 'church-management-cbf7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIXqkAoYFP-weaIiDsUR_kW1AoltWsIZY',
    appId: '1:804008888688:ios:9697ba392ee24ea07a67b5',
    messagingSenderId: '804008888688',
    projectId: 'church-management-cbf7d',
    databaseURL: 'https://church-management-cbf7d-default-rtdb.firebaseio.com',
    storageBucket: 'church-management-cbf7d.appspot.com',
    androidClientId: '804008888688-9nt22c34rameeavgg3r142cvgvas53vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChurchManagement',
  );
}
